# Generated by Django 6.0.4 on 2026-04-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jwt_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
