# Generated by Django 6.0.4 on 2026-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_jwt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_last_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
