# Generated by Django 6.0.4 on 2026-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobinteractionstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='level',
        ),
        migrations.AddField(
            model_name='job',
            name='required_experience_fields',
            field=models.TextField(blank=True, help_text='Comma-separated fields/tech stack (e.g. React, Django, PostgreSQL)'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum years of experience required', null=True),
        ),
    ]
