# Generated by Django 6.0.4 on 2026-07-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_description_job_work_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_job_application_per_user',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
