# Generated by Django 6.0.4 on 2026-07-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_job_description_job_work_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_snapshot', models.FileField(blank=True, help_text='Immutable copy of the resume used at the time of application.', null=True, upload_to='application_resumes/')),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter content submitted with this application.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_to_apply', 'Ready to Apply'), ('applied', 'Applied'), ('under_review', 'Under Review'), ('recruiter_contacted', 'Recruiter Contacted'), ('oa_scheduled', 'OA Scheduled'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', help_text='Current status in the application lifecycle.', max_length=30)),
                ('applied_at', models.DateTimeField(blank=True, help_text="Timestamp when status moved to 'applied'.", null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Quick notes about this application.')),
                ('recruiter_name', models.CharField(blank=True, default='', help_text='Name of the recruiter or hiring contact.', max_length=255)),
                ('recruiter_email', models.EmailField(blank=True, default='', help_text='Email of the recruiter or hiring contact.', max_length=254)),
                ('interview_date', models.DateTimeField(blank=True, help_text='Next upcoming interview date.', null=True)),
                ('offer_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Offered salary amount.', max_digits=12, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Expected/desired salary amount.', max_digits=12, null=True)),
                ('source', models.CharField(choices=[('company_website', 'Company Website'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('referral', 'Referral'), ('career_fair', 'Career Fair'), ('recruiter', 'Recruiter'), ('jobseek', 'JobSeek'), ('other', 'Other')], default='other', help_text='How the user discovered this job opening.', max_length=30)),
                ('archived', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Archived applications are hidden from default views.')),
                ('withdrawn', models.BooleanField(default=False, help_text='Whether the user has withdrawn this application.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='The job listing this application is for.', on_delete=django.db.models.deletion.CASCADE, related_name='application_records', to='jobs.job')),
                ('user', models.ForeignKey(help_text='The user who submitted this application.', on_delete=django.db.models.deletion.CASCADE, related_name='tracked_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'applications_job_application',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Sequential round number (1, 2, 3, ...).')),
                ('interview_type', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('manager', 'Manager'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('coding', 'Coding'), ('online_assessment', 'Online Assessment')], help_text='Type of interview for this round.', max_length=30)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Scheduled date and time for this interview.', null=True)),
                ('interviewer', models.CharField(blank=True, default='', help_text='Name of the interviewer.', max_length=255)),
                ('location', models.CharField(blank=True, default='', help_text='Interview location (physical address or video call URL).', max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', help_text='Current status of this interview round.', max_length=20)),
                ('feedback', models.TextField(blank=True, default='', help_text='Post-interview feedback or notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='The parent application this round belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Interview Round',
                'verbose_name_plural': 'Interview Rounds',
                'db_table': 'applications_interview_round',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Application Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('follow_up', 'Follow Up'), ('recruiter_contacted', 'Recruiter Contacted'), ('custom', 'Custom Event')], help_text='Categorized type of this timeline event.', max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this event occurred.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this event (null if system-generated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(help_text='The parent application this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'applications_timeline',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='The note content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The user who wrote this note.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(help_text='The parent application this note belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Application Note',
                'verbose_name_plural': 'Application Notes',
                'db_table': 'applications_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_package', models.DecimalField(blank=True, decimal_places=2, help_text='Total compensation package (CTC).', max_digits=12, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Base salary amount.', max_digits=12, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, help_text='Annual bonus amount.', max_digits=12, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, help_text='Stock/equity compensation value.', max_digits=12, null=True)),
                ('joining_bonus', models.DecimalField(blank=True, decimal_places=2, help_text='One-time joining/signing bonus.', max_digits=12, null=True)),
                ('location', models.CharField(blank=True, default='', help_text='Office location for this offer.', max_length=255)),
                ('remote', models.BooleanField(default=False, help_text='Whether this is a remote position.')),
                ('joining_date', models.DateField(blank=True, help_text='Expected start/joining date.', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Deadline to accept or decline the offer.', null=True)),
                ('accepted', models.BooleanField(blank=True, help_text='None = pending, True = accepted, False = declined.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(help_text='The application this offer is for.', on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'applications_offer',
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='idx_app_user_status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'archived'], name='idx_app_user_archived'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'created_at'], name='idx_app_user_created'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'applied_at'], name='idx_app_user_applied'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'updated_at'], name='idx_app_status_updated'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_application_per_user_job'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['application', 'scheduled_time'], name='idx_interview_app_time'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['scheduled_time', 'status'], name='idx_interview_time_status'),
        ),
        migrations.AddConstraint(
            model_name='interviewround',
            constraint=models.UniqueConstraint(fields=('application', 'round_number'), name='unique_interview_round_per_application'),
        ),
        migrations.AddIndex(
            model_name='applicationtimeline',
            index=models.Index(fields=['application', 'timestamp'], name='idx_timeline_app_ts'),
        ),
        migrations.AddIndex(
            model_name='applicationtimeline',
            index=models.Index(fields=['application', 'event_type'], name='idx_timeline_app_type'),
        ),
    ]
