# Generated by Django 6.0.4 on 2026-04-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_savedjob_viewedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInteractionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('viewed_count', models.PositiveIntegerField(default=0)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_stats', to='jobs.job')),
            ],
        ),
    ]
