# Generated by Django 6.0.4 on 2026-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_level_job_required_experience_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Full job description'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote / Work from Home'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
    ]
