# Generated by Django 6.0.4 on 2026-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_github_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('language', 'Language'), ('other', 'Other')], max_length=20),
        ),
    ]
